TaskCalendar/Models/DataViewListTask.cs
using Domain.Entities;
using Domain.Models;
using System;
using System.Collections.Generic;

namespace TaskCalendar.Models
{
    public class DataViewListTask
    {
        public List<TodoTask> Tasks { get; set; }
        public List<TimeDTO> DropDownTimes { get; set; }
        public DateTime SelectedDate { get; internal set; }
    }
}

TaskCalendar/Models/DateGrid.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TaskCalendar.Models
{
    public class DateGrid
    {
        public DateTime SelectedViewDate { get; set; }
        public List<DayCol> Days { get; set; }


        public static List<DayCol> GetListShowingDays(
            DateTime dateTime, List<IGrouping<DateTime, TodoTask>> groupDaysTasks)
        {
            dateTime = GetPrevMonthDateForGrid(dateTime);

            List<DayCol> listDayCol = new List<DayCol>();

            int gridDays = 7 * 6;
            for (int i = 0; i < gridDays; i++)
            {
                if (IsTaskExists(dateTime, groupDaysTasks))
                {
                    var groupTasks =
                        groupDaysTasks
                        .Where(dt => dt.Key.Date == dateTime.Date)
                        .FirstOrDefault();

                    listDayCol.Add(
                        new DayCol
                        {
                            Date = dateTime,
                            QuantityTask = groupTasks.Count()
                        }
                        );
                }
                else
                {
                    listDayCol.Add(
                        new DayCol
                        {
                            Date = dateTime,
                            QuantityTask = 0
                        }
                        );
                }
                dateTime = dateTime.AddDays(1);
            }

            return listDayCol;
        }

        public static DateTime GetPrevMonthDateForGrid(DateTime dateTime)
        {
            int dayOfWeek = (int)dateTime.DayOfWeek == 0 
                ? 7 
                : (int)dateTime.DayOfWeek;

            int prevMonthDay = dayOfWeek - 1;
            dateTime = dateTime.AddDays(-prevMonthDay);
            return dateTime;
        }

        private static bool IsTaskExists(
            DateTime dateTime,
            List<IGrouping<DateTime, TodoTask>> groupDaysTasks)
        {
            foreach (var group in groupDaysTasks)
            {
                if (group.Key.Date == dateTime.Date)
                {
                    return true;
                }
            }

            return false;
        }
    }
}

TaskCalendar/Models/DayCol.cs
using System;

namespace TaskCalendar.Models
{
    public class DayCol
    {
        public DateTime Date { get; set; }
        public int QuantityTask { get; set; }
    }
}

TaskCalendar/Models/ErrorViewModel.cs
using System;

namespace TaskCalendar.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TaskCalendar/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.Abstract;
using Domain.Entities;
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using TaskCalendar.Models;

namespace TaskCalendar.Controllers
{
    public class CalendarController : Controller
    {
        private ITodoTaskRepository taskRepository;
        // Default for testing
        private const int CURRENT_YEAR = 2020;
        private const int CURRENT_MONTH = 10;

        public CalendarController(ITodoTaskRepository _taskRepository)
        {
            taskRepository = _taskRepository;
        }

        public ViewResult Grid(int y = CURRENT_YEAR, int m = CURRENT_MONTH)
        {
            DateTime selectedDate = new DateTime(y, m, 1);

            List<IGrouping<DateTime, TodoTask>> groupDaysTasks
                = taskRepository.GetTasksForEachDay(
                    DateGrid.GetPrevMonthDateForGrid(selectedDate),
                    6 * 7);

            DateGrid dateGrid = new DateGrid
            {
                SelectedViewDate = selectedDate,
                Days = DateGrid.GetListShowingDays(
                    selectedDate,
                    groupDaysTasks)
            };

            return View(dateGrid);
        }

        public ViewResult ListTasksForDay(int y, int m, int d)
        {
            DateTime selectedDate = new DateTime(y, m, d);

            List<TodoTask> tasks = taskRepository
                .GetTasksInADay(selectedDate);

            DataViewListTask dataViewList
                = new DataViewListTask
                {
                    SelectedDate = selectedDate,
                    Tasks = tasks,
                    DropDownTimes = taskRepository.GetTimesDay()
                };

            return View(dataViewList);
        }

        [HttpPost]
        public ActionResult Add(string time, string description, DateTime curDate)
        {
            try
            {
                TimeDTO timeDTO = new TimeDTO(time);
                DateTime date = new DateTime(
                    curDate.Year, curDate.Month, curDate.Day,
                    timeDTO.Hour, timeDTO.Minute, 0);
                TodoTask newTask = new TodoTask
                {
                    DateTime = date,
                    Description = description
                };
                taskRepository.Add(newTask);

                return RedirectToAction($"ListTasksForDay", 
                    new { 
                        y = curDate.Year,
                        m = curDate.Month,
                        d = curDate.Day
                    } 
                    );
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Delete(int id, DateTime dateTime)
        {
            try
            {
                taskRepository.Delete(id);

                return RedirectToAction($"ListTasksForDay",
                    new
                    {
                        y = dateTime.Year,
                        m = dateTime.Month,
                        d = dateTime.Day
                    });
            }
            catch
            {
                return View();
            }
        }
    }
}

TaskCalendar/Views/Calendar/Grid.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Grid";
}

@model DateGrid

<h1>Grid</h1>

<table class="table table-bordered text-center">
    <thead>
        <tr>
            <th><a href="/?y=@Model.SelectedViewDate.Year&m=@Model.SelectedViewDate.AddMonths(-1).Month"><=</a></th>
            <th colspan="5">@Model.SelectedViewDate.ToString("MMMM yyyy")</th>
            <th><a href="/?y=@Model.SelectedViewDate.Year&m=@Model.SelectedViewDate.AddMonths(1).Month">=></a></th>
        </tr>
    </thead>
    <tbody>
        @for (int w = 0, i = 0; w < 6; w++)
        {
            @:<tr>
                for (int d = 0; d < 7; d++, i++)
                {
                    @:<td @if (Model.Days[i].Date.Month != Model.SelectedViewDate.Month)
                    {
                        @:class="table-secondary"
                    }>
        <a href="/Calendar/ListTasksForDay?y=@Model.Days[i].Date.Year&m=@Model.Days[i].Date.Month&d=@Model.Days[i].Date.Day">
        @Model.Days[i].Date.Day</a>
                        @if (Model.Days[i].QuantityTask > 0)
                        {
                            @:<span class="quantityTask">(@Model.Days[i].QuantityTask)</span>
                        }
                    @:</td>
                }
            @:</tr>
        }
    </tbody>
</table>

TaskCalendar/Views/Calendar/List.cshtml
@{ 
    Layout = "_Layout";
}

@using Domain.Entities
@model IEnumerable<TodoTask>

@foreach (var item in Model)
	{
		 <div>
             <div>@item.Description</div>
		 </div>
	}

TaskCalendar/Views/Calendar/ListTasksForDay.cshtml
@model DataViewListTask

@{
    ViewData["Title"] = "ListTasksForDay";
}

<h1>ListTasksForDay</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Tasks[0].DateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tasks[0].Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Tasks) {
        <tr>
            <td>
                @item.DateTime.ToString("dd.MM.yyyy HH:mm")
            </td>
            <td>
                @item.Description
            </td>
            <td>
                <form action="Delete" method="post">
                    <input type="hidden" name="id" value="@item.TodoTaskID" />
                    <input type="hidden" name="dateTime" value="@item.DateTime" />
                    <input type="submit" value="Delete" class="btn btn-warning"/>
                </form>
            </td>
        </tr>
}
    </tbody>
</table>

<div>

    <h2 class="mb-3">Add task</h2>
    <form action="Add" method="post" class="form-inline row">
        <div class="form-group mr-4 col-1">
            <label class="sr-only">DateTime</label>
            <select class="form-control" name="time" asp-items="@new SelectList(Model.DropDownTimes)"></select>
        </div>
        <div class="form-group mr-4 col-6">
            <label class="sr-only">Description</label>
            <input type="text" name="description" value="" class="form-control col-12"/>
        </div>
        <input type="hidden" name="curDate" value="@Model.SelectedDate" />
        <input type="submit" value="Add" class="btn btn-success"/>
    </form>
</div>

TaskCalendar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskCalendar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskCalendar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="Grid">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TaskCalendar
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>